" Note: Skip initialization for vim-tiny or vim-small.
if 0 | endif

" Autoinstall vim-plug 
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugin sources -------------------------
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive' 
Plug 'vim-airline/vim-airline' 
Plug 'vim-airline/vim-airline-themes' 
Plug 'morhetz/gruvbox'
call plug#end()

" Airline Settings-------------------------
" Show vim-airline bar the whole time
set laststatus=2
set encoding=utf-8
set guifont=Droid\ Sans\ Mono\ Powerline
let g:airline_powerline_fonts = 1
let g:airline_theme = 'minimalist'
let g:airline_extensions = ['branch', 'tabline']
" End Airline Settings---------------------



" -----------------------
" VIM Basic Configuration
" -----------------------

" Reload files which where modified outside of VIM
if !exists("autocommands_loaded")
  let autocommands_loaded=1
  autocmd BufEnter * checktime
endif

" UX settings ------------
set path=$PWD/** " search in current folder and subfolders
set wildmenu
set relativenumber
set number
colorscheme gruvbox
set background=dark

" formatting settins ----
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab " use spaces for tabs

" Tweaks for file browsing
let g:netrw_banner=1
let g:netrw_liststyle=3

" Source vim config in the local directory
silent! so .vimlocal
